### ISSUE TITLE
docs: outline how it works

### ISSUE THREAD

**Issue by MentalGear** [duplojs/zod-accelerator#53]
The benchmarks seem very impressive. It would be nice though if you could outline in a few lines how you managed to achieve this, and what the trade-offs are. This would boost confidence and help assessing whether this lib is a fit or not.

**Comment by mathcovax** [comment]
Hello, yes indeed, that would be a good idea. I will take care of it when I have some time !

**Comment by MentalGear** [comment]
👍 On 18 Oct 2024, at 15:56, mathcovax ***@***.***> wrote:﻿
Closed #53 as completed.
